export const PLATFORM_MANAGEMENT_START = 'PLATFORM_MANAGEMENT_START';
export const PLATFORM_MANAGEMENT_FAIL = 'PLATFORM_MANAGEMENT_FAIL';

export const GET_PLATFORM_MANAGEMENT_EARN_LIST_SAGA = 'GET_PLATFORM_MANAGEMENT_EARN_LIST_SAGA';
export const GET_PLATFORM_MANAGEMENT_EARN_LIST_SUCCESS =
  'GET_PLATFORM_MANAGEMENT_EARN_LIST_SUCCESS';

export const GET_PLATFORM_MANAGEMENT_LENDING_LIST_SAGA =
  'GET_PLATFORM_MANAGEMENT_LENDING_LIST_SAGA';
export const GET_PLATFORM_MANAGEMENT_LENDING_LIST_SUCCESS =
  'GET_PLATFORM_MANAGEMENT_LENDING_LIST_SUCCESS';

export const GET_PLATFORM_MANAGEMENT_SWAP_LIST_SAGA = 'GET_PLATFORM_MANAGEMENT_SWAP_LIST_SAGA';
export const GET_PLATFORM_MANAGEMENT_SWAP_LIST_SUCCESS =
  'GET_PLATFORM_MANAGEMENT_SWAP_LIST_SUCCESS';

export const GET_PLATFORM_MANAGEMENT_LOAN_LIST_SAGA = 'GET_PLATFORM_MANAGEMENT_LOAN_LIST_SAGA';
export const GET_PLATFORM_MANAGEMENT_LOAN_LIST_SUCCESS =
  'GET_PLATFORM_MANAGEMENT_LOAN_LIST_SUCCESS';
