export const ADMIN_START = 'ADMIN_START';
export const ADMIN_FAIL = 'ADMIN_FAIL';

export const ADMIN_ACTION_START = 'ADMIN_ACTION_START';
export const ADMIN_ACTION_FAIL = 'ADMIN_ACTION_FAIL';

export const GET_ADMIN_LIST_SAGA = 'GET_ADMIN_LIST_SAGA';
export const GET_ADMIN_LIST_SUCCESS = 'GET_ADMIN_LIST_SUCCESS';

export const ADD_ADMIN_SAGA = 'ADD_ADMIN_SAGA';
export const ADD_ADMIN_SUCCESS = 'ADD_ADMIN_SUCCESS';

export const UPDATE_ADMIN_SAGA = 'UPDATE_ADMIN_SAGA';
export const UPDATE_ADMIN_SUCCESS = 'UPDATE_ADMIN_SUCCESS';

export const GET_ADMIN_DETAILS_SAGA = 'GET_ADMIN_DETAILS_SAGA';
export const GET_ADMIN_DETAILS_SUCCESS = 'GET_ADMIN_DETAILS_SUCCESS';

export const DELETE_ADMIN_SAGA = 'DELETE_ADMIN_SAGA';
export const DELETE_ADMIN_SUCCESS = 'DELETE_ADMIN_SUCCESS';

export const UPDATE_STATUS_ADMIN_SAGA = 'UPDATE_STATUS_ADMIN_SAGA';
export const UPDATE_STATUS_ADMIN_SUCCESS = 'UPDATE_STATUS_ADMIN_SUCCESS';

export const TEMP_PWD_SAGA = 'TEMP_PWD_SAGA';
export const TEMP_PWD_SUCCESS = 'TEMP_PWD_SUCCESS';

export const GET_CARD_DATA_START = 'GET_CARD_DATA_START';
export const GET_CARD_DATA_FAIL = 'GET_CARD_DATA_FAIL';
export const GET_CARD_DATA_SAGA = 'GET_CARD_DATA_SAGA';
export const GET_CARD_DATA_SUCCESS = 'GET_CARD_DATA_SUCCESS';
