// Count
export const DASHBOARD_COUNT_DATA_START = 'DASHBOARD_COUNT_DATA_START';
export const DASHBOARD_COUNT_DATA_FAIL = 'DASHBOARD_COUNT_DATA_FAIL';
export const DASHBOARD_COUNT_DATA_SUCCESS = 'DASHBOARD_COUNT_DATA_SUCCESS';
export const DASHBOARD_COUNT_DATA_SAGA = 'DASHBOARD_COUNT_DATA_SAGA';

// Profit
export const DASHBOARD_PROFIT_DATA_START = 'DASHBOARD_PROFIT_DATA_START';
export const DASHBOARD_PROFIT_DATA_FAIL = 'DASHBOARD_PROFIT_DATA_FAIL';
export const DASHBOARD_PROFIT_DATA_SUCCESS = 'DASHBOARD_PROFIT_DATA_SUCCESS';
export const DASHBOARD_PROFIT_DATA_SAGA = 'DASHBOARD_PROFIT_DATA_SAGA';

// Loan overview
export const DASHBOARD_LOAN_DATA_START = 'DASHBOARD_LOAN_DATA_START';
export const DASHBOARD_LOAN_DATA_FAIL = 'DASHBOARD_LOAN_DATA_FAIL';
export const DASHBOARD_LOAN_DATA_SUCCESS = 'DASHBOARD_LOAN_DATA_SUCCESS';
export const DASHBOARD_LOAN_DATA_SAGA = 'DASHBOARD_LOAN_DATA_SAGA';

// Swap overview
export const DASHBOARD_SWAP_DATA_START = 'DASHBOARD_SWAP_DATA_START';
export const DASHBOARD_SWAP_DATA_FAIL = 'DASHBOARD_SWAP_DATA_FAIL';
export const DASHBOARD_SWAP_DATA_SUCCESS = 'DASHBOARD_SWAP_DATA_SUCCESS';
export const DASHBOARD_SWAP_DATA_SAGA = 'DASHBOARD_SWAP_DATA_SAGA';

// Earn overview
export const DASHBOARD_EARN_DATA_START = 'DASHBOARD_EARN_DATA_START';
export const DASHBOARD_EARN_DATA_FAIL = 'DASHBOARD_EARN_DATA_FAIL';
export const DASHBOARD_EARN_DATA_SUCCESS = 'DASHBOARD_EARN_DATA_SUCCESS';
export const DASHBOARD_EARN_DATA_SAGA = 'DASHBOARD_EARN_DATA_SAGA';

// Collateral chart
export const DASHBOARD_COLLATERAL_DATA_START = 'DASHBOARD_COLLATERAL_DATA_START';
export const DASHBOARD_COLLATERAL_DATA_FAIL = 'DASHBOARD_COLLATERAL_DATA_FAIL';
export const DASHBOARD_COLLATERAL_DATA_SUCCESS = 'DASHBOARD_COLLATERAL_DATA_SUCCESS';
export const DASHBOARD_COLLATERAL_DATA_SAGA = 'DASHBOARD_COLLATERAL_DATA_SAGA';

// Balance chart
export const DASHBOARD_BALANCE_DATA_START = 'DASHBOARD_BALANCE_DATA_START';
export const DASHBOARD_BALANCE_DATA_FAIL = 'DASHBOARD_BALANCE_DATA_FAIL';
export const DASHBOARD_BALANCE_DATA_SUCCESS = 'DASHBOARD_BALANCE_DATA_SUCCESS';
export const DASHBOARD_BALANCE_DATA_SAGA = 'DASHBOARD_BALANCE_DATA_SAGA';

// Global data
export const DASHBOARD_GLOBAL_DATA_START = 'DASHBOARD_GLOBAL_DATA_START';
export const DASHBOARD_GLOBAL_DATA_FAIL = 'DASHBOARD_GLOBAL_DATA_FAIL';
export const DASHBOARD_GLOBAL_DATA_SUCCESS = 'DASHBOARD_GLOBAL_DATA_SUCCESS';
export const DASHBOARD_GLOBAL_DATA_SAGA = 'DASHBOARD_GLOBAL_DATA_SAGA';
