export const GET_PLAT_VARIABLE_START = 'GET_PLAT_VARIABLE_START';
export const GET_PLAT_VARIABLE_FAIL = 'GET_PLAT_VARIABLE_FAIL';

export const ADD_PLAT_VARIABLE_SAGA = 'ADD_PLAT_VARIABLE_SAGA';
export const ADD_PLAT_VARIABLE_SUCCESS = 'ADD_PLAT_VARIABLE_SUCCESS';

export const UPDATE_PLAT_VARIABLE_SAGA = 'UPDATE_PLAT_VARIABLE_SAGA';
export const UPDATE_PLAT_VARIABLE_SUCCESS = 'UPDATE_PLAT_VARIABLE_SUCCESS';

export const GET_SINGLE_PLAT_VARIABLE_SAGA = 'GET_SINGLE_PLAT_VARIABLE_SAGA';
export const GET_SINGLE_PLAT_VARIABLE_SUCCESS = 'GET_SINGLE_PLAT_VARIABLE_SUCCESS';

export const GET_PLAT_VARIABLE_LIST_SAGA = 'GET_PLAT_VARIABLE_LIST_SAGA';
export const GET_PLAT_VARIABLE_LIST_SUCCESS = 'GET_PLAT_VARIABLE_LIST_SUCCESS';

export const GET_PLAT_VARIABLE_ACTIVITY_HISTORY_SAGA = 'GET_PLAT_VARIABLE_ACTIVITY_HISTORY_SAGA';
export const GET_PLAT_VARIABLE_ACTIVITY_HISTORY_SUCCESS =
  'GET_PLAT_VARIABLE_ACTIVITY_HISTORY_SUCCESS';

export const GET_PLAT_VARIABLE_ACTIVITY_START = 'GET_PLAT_VARIABLE_ACTIVITY_START';
export const GET_PLAT_VARIABLE_ACTIVITY_FAIL = 'GET_PLAT_VARIABLE_ACTIVITY_FAIL';
