export const GET_EARLY_USER = 'GET_EARLY_USER';
export const GET_EARLY_USER_SUCCESS = 'GET_EARLY_USER_SUCCESS';
export const GET_EARLY_USER_START = 'GET_EARLY_USER_START';
export const GET_EARLY_USER_FAIL = 'GET_EARLY_USER_FAIL';
export const SEND_PASSWORD = 'SEND_PASSWORD';
export const SEND_PASSWORD_START = 'SEND_PASSWORD_START';
export const SEND_PASSWORD_FAIL = 'SEND_PASSWORD_FAIL';
export const SEND_PASSWORD_SUCCESS = 'SEND_PASSWORD_SUCCESS';
export const ADD_INVESTOR = 'ADD_INVESTOR';
export const ADD_INVESTOR_START = 'ADD_INVESTOR_START';
export const ADD_INVESTOR_SUCCESS = 'ADD_INVESTOR_SUCCESS';
export const ADD_INVESTOR_FAIL = 'ADD_INVESTOR_FAIL';
export const SAVED_ITEM = 'SAVED_ITEM';
export const BLACK_WHITE_LIST = 'BLACK_WHITE_LIST';
export const BLACK_WHITE_LIST_START = 'BLACK_WHITE_LIST_START';
export const BLACK_WHITE_LIST_SUCCESS = 'BLACK_WHITE_LIST_SUCCESS';
export const BLACK_WHITE_LIST_FAIL = 'BLACK_WHITE_LIST_FAIL';

// USER

export const USER_START = 'USER_START';
export const USER_FAIL = 'USER_FAIL';

export const USER_ACTION_START = 'USER_ACTION_START';
export const USER_ACTION_FAIL = 'USER_ACTION_FAIL';

export const GET_USER_LIST_SAGA = 'GET_USER_LIST_SAGA';
export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS';

export const ADD_USER_SAGA = 'ADD_USER_SAGA';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';

export const UPDATE_USER_SAGA = 'UPDATE_USER_SAGA';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const GET_USER_DETAILS_SAGA = 'GET_USER_DETAILS_SAGA';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';

export const DELETE_USER_SAGA = 'DELETE_USER_SAGA';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';

export const GET_WALLET_LIST_SAGA = 'GET_WALLET_LIST_SAGA';
export const GET_WALLET_LIST_SUCCESS = 'GET_WALLET_LIST_SUCCESS';

export const GET_LOAN_LIST_SAGA = 'GET_LOAN_LIST_SAGA';
export const GET_LOAN_LIST_SUCCESS = 'GET_LOAN_LIST_SUCCESS';

export const GET_LENDING_LIST_SAGA = 'GET_LENDING_LIST_SAGA';
export const GET_LENDING_LIST_SUCCESS = 'GET_LENDING_LIST_SUCCESS';

export const SEND_EMAIL_TO_USER_SAGA = 'SEND_EMAIL_TO_USER_SAGA';
export const SEND_EMAIL_TO_USER_SUCCESS = 'SEND_EMAIL_TO_USER_SUCCESS';

export const SEND_GIFT_TO_USER_SAGA = 'SEND_GIFT_TO_USER_SAGA';
export const SEND_GIFT_TO_USER_SUCCESS = 'SEND_GIFT_TO_USER_SUCCESS';

// export const TEMP_PWD_SAGA = 'TEMP_PWD_SAGA';
// export const TEMP_PWD_SUCCESS = 'TEMP_PWD_SUCCESS';
