export const currentPropertiesData = [
  {
    srno: 1,
    propertyName: 'Lame House',
    state: 'California',
    country: 'Los Angeles',
    startDate: '10/02/2022',
    propertyFee: '10%',
    TokensOwned: '15000',
    value: '$100',
    owned: '20%',
    duration: '12 months',
  },
  {
    srno: 2,
    propertyName: 'Lame House',
    state: 'California',
    country: 'Los Angeles',
    startDate: '10/02/2022',
    propertyFee: '10%',
    TokensOwned: '15000',
    value: '$100',
    owned: '20%',
    duration: '12 months',
  },
  {
    srno: 3,
    propertyName: 'Lame House',
    state: 'California',
    country: 'Los Angeles',
    startDate: '10/02/2022',
    propertyFee: '10%',
    TokensOwned: '15000',
    value: '$100',
    owned: '20%',
    duration: '12 months',
  },
  {
    srno: 4,
    propertyName: 'Lame House',
    state: 'California',
    country: 'Los Angeles',
    startDate: '10/02/2022',
    propertyFee: '10%',
    TokensOwned: '15000',
    value: '$100',
    owned: '20%',
    duration: '12 months',
  },
  {
    srno: 5,
    propertyName: 'Lame House',
    state: 'California',
    country: 'Los Angeles',
    startDate: '10/02/2022',
    propertyFee: '10%',
    TokensOwned: '15000',
    value: '$100',
    owned: '20%',
    duration: '12 months',
  },
  {
    srno: 6,
    propertyName: 'Lame House',
    state: 'California',
    country: 'Los Angeles',
    startDate: '10/02/2022',
    propertyFee: '10%',
    TokensOwned: '15000',
    value: '$100',
    owned: '20%',
    duration: '12 months',
  },
];
