export const draftData = [
  {
    title: 'Property title',
    email: 'test@gmailcom',
    location: 'California',
    name: 'Tiger Nixon',
    state: 'Califonia',
    city: 'Edinburgh',
    ownerName: 'John',
    propertyType: 'Apartment',
    lastUpdatedOn: '2011/04/25',
  },
  {
    title: 'Property title',
    email: 'test@gmailcom',
    location: 'California',
    name: 'Tiger Nixon',
    state: 'Califonia',
    city: 'Edinburgh',
    ownerName: 'John',
    propertyType: 'Apartment',
    lastUpdatedOn: '2011/04/25',
  },
  {
    title: 'Property title',
    email: 'test@gmailcom',
    location: 'California',
    name: 'Tiger Nixon',
    state: 'johanisberg',
    city: 'Edinburgh',
    ownerName: 'John',
    propertyType: 'Apartment',
    lastUpdatedOn: '2011/04/25',
  },
  {
    title: 'Property title',
    email: 'test@gmailcom',
    location: 'California',
    name: 'Tiger Nixon',
    state: 'Califonia',
    city: 'Edinburgh',
    ownerName: 'John',
    propertyType: 'Apartment',
    lastUpdatedOn: '2011/04/25',
  },
  {
    title: 'Property title',
    email: 'test@gmailcom',
    location: 'California',
    name: 'Tiger Nixon',
    state: 'Califonia',
    city: 'Edinburgh',
    ownerName: 'John',
    propertyType: 'Apartment',
    lastUpdatedOn: '2011/04/25',
  },
  {
    title: 'Property title',
    email: 'test@gmailcom',
    location: 'California',
    name: 'Tiger Nixon',
    state: 'Califonia',
    city: 'Edinburgh',
    ownerName: 'John',
    propertyType: 'Apartment',
    lastUpdatedOn: '2011/04/25',
  },
  {
    title: 'Property title',
    email: 'test@gmailcom',
    location: 'California',
    name: 'Tiger Nixon',
    state: 'Califonia',
    city: 'Edinburgh',
    ownerName: 'John',
    propertyType: 'Apartment',
    lastUpdatedOn: '2011/04/25',
  },
  {
    title: 'Property title',
    email: 'test@gmailcom',
    location: 'California',
    name: 'Tiger Nixon',
    state: 'Califonia',
    city: 'Edinburgh',
    ownerName: 'John',
    propertyType: 'Apartment',
    lastUpdatedOn: '2011/04/25',
  },
  {
    title: 'Property title',
    email: 'test@gmailcom',
    location: 'California',
    name: 'Tiger Nixon',
    state: 'Califonia',
    city: 'Edinburgh',
    ownerName: 'John',
    propertyType: 'Apartment',
    lastUpdatedOn: '2011/04/25',
  },
  {
    title: 'Property title',
    email: 'test@gmailcom',
    location: 'California',
    name: 'Tiger Nixon',
    state: 'Califonia',
    city: 'Edinburgh',
    ownerName: 'John',
    propertyType: 'Apartment',
    lastUpdatedOn: '2011/04/25',
  },
  {
    title: 'Property title',
    email: 'test@gmailcom',
    location: 'California',
    name: 'Tiger Nixon',
    state: 'Califonia',
    city: 'Edinburgh',
    ownerName: 'John',
    propertyType: 'Apartment',
    lastUpdatedOn: '2011/04/25',
  },
];

export const sideBarItem = [
  {
    name: 'Property Details',
    tabid: [1, 9],
    propertyTab: true,
  },
  {
    name: 'Financials',
    tabid: [2],
    propertyTab: true,
  },
  {
    name: 'Document',
    tabid: [3],
    propertyTab: true,
  },
  {
    name: 'Images',
    tabid: [4],
    propertyTab: true,
  },
  {
    name: 'Crowdsale',
    tabid: [5],
    propertyTab: true,
  },
  {
    name: 'Buy Process',
    tabid: [7],
    propertyTab: true,
  },
  {
    name: 'Cashflow',
    tabid: [6],
    propertyTab: true,
  },
  {
    name: 'Market Detail',
    tabid: [8],
    showOnmarket: true,
  },
];

export const propertyData = {
  _id: '635b5ac2438006881c1482bc',
  attom: {
    attomId: 123,
    apn: '04103-0059',
    lotsize1: 0.0533517,
    lotsize2: 2324,
    area: 1820,
    lotnum: '59',
    blockNumber: '4103',
    locationType: 'VIEW - NONE',
    country: 'US',
    areaTaxCode: '1',
    line1: '183 ETNA ST',
    line2: 'BROOKLYN, NY 11208',
    zipCode: '11208',
    latitude: '40.686262',
    longitude: '-73.876857',
    propertyClass: 'Single Family Residence / Townhouse',
    propertyType: 'SFR',
    yearBuilt: 1901,
    levels: 2,
    avmlastmonthvalue: 773144,
    avmamountchange: 98960,
    avmpercentchange: 12,
    city: 'BROOKLYN',
    state: 'NY',
    bedrooms: 5,
    bathTotal: 4,
  },
  otherInfo: {
    isOccupied: false,
    tags: ['High Growth', 'Cash Flowing', 'Stable'],
    pool: false,
    fireplace: false,
    garage: false,
    descriptionHeading: 'THE FIRST',
    descriptionSubHeading: 'This is sub heading',
    description: 'This is test description for property',
    _market: '6350d1f3109bdf7c59722d93',
    title: 'Omega 1',
  },
  financials: {
    propertyValues: [
      {
        updatedAt: '2022-10-28T04:29:54.736Z',
        value: 564600,
      },
    ],
    currentEquity: 100000,
    currentDebt: 400000,
    assetValue: 500000,
    closingCost: 18000,
    maintenanceReserve: 22000,
    vacancyReserve: 16000,
    yearlyReturn: '18',
    defaultRentGrowth: '10',
    defaultAnnualAppreciation: '10',
    defaultTokensPurchased: 10000,
    interest: '6.5',
    loanTerm: '36',
    projectedInvestmentGain: '100',
    mogulBuyerFee: 8600,
    mogulSellerFee: 5000,
    sellerEquity: 32920,
    mogulEquityToBuy: 16460,
    platformEquityToSell: 115220,
    leveragedCashflowMargin: '25',
    defaultMonthlyRent: 5000,
    contingencyVar1: {
      applicable: false,
      _id: '63624541327d45ae763c2e71',
    },
    contingencyVar2: {
      applicable: false,
      _id: '63624541327d45ae763c2e72',
    },
    contingencyVar3: {
      applicable: false,
      _id: '63624541327d45ae763c2e73',
    },
    contingencyVar4: {
      applicable: false,
      _id: '63624541327d45ae763c2e74',
    },
  },
  documents: {
    others: [
      {
        contentType: 'application/pdf',
        key: 'documents/Admin MogulMVP Wireframes ( 1 )-1667383930361.pdf',
        url: 'https://mogul-property-details.s3.amazonaws.com/documents/Admin%20MogulMVP%20Wireframes%20%28%201%20%29-1667383930361.pdf',
        sizeInMegaByte: 2291440,
        _id: '63624541327d45ae763c2e7a',
        createdAt: '2022-11-02T10:24:01.818Z',
      },
    ],
    main: {
      _id: '63624541327d45ae763c2e79',
      createdAt: '2022-11-02T10:24:01.815Z',
      contentType: 'application/pdf',
      key: 'mainDoc/Mogul Admin Wireframes 0-1667383930269.pdf',
      url: 'https://mogul-property-details.s3.amazonaws.com/mainDoc/Mogul%20Admin%20Wireframes%200-1667383930269.pdf',
      sizeInMegaByte: 2664621,
    },
  },
  images: {
    list: [
      {
        contentType: 'image/png',
        key: 'images/mnist_0-1667383930417.webp',
        url: 'https://mogul-property-details.s3.amazonaws.com/images/mnist_0-1667383930417.webp',
        sizeInMegaByte: 1728,
        _id: '63624541327d45ae763c2e7b',
        createdAt: '2022-11-02T10:24:01.819Z',
      },
      {
        contentType: 'image/jpeg',
        key: 'images/Part39-1667383930430.webp',
        url: 'https://mogul-property-details.s3.amazonaws.com/images/Part39-1667383930430.webp',
        sizeInMegaByte: 13080,
        _id: '63624541327d45ae763c2e7c',
        createdAt: '2022-11-02T10:24:01.820Z',
      },
    ],
    mainImage: 0,
  },
  cashflow: {
    monthlyRent: [],
    rentalDocuments: [
      {
        updatedAt: '2022-11-02T10:24:01.812Z',
        value: {
          contentType: 'application/pdf',
          key: 'rentalDocument/Admin MogulMVP ( 0 )-1667383930330.pdf',
          url: 'https://mogul-property-details.s3.amazonaws.com/rentalDocument/Admin%20MogulMVP%20%28%200%20%29-1667383930330.pdf',
          sizeInMegaByte: 1308854,
          _id: '63624541327d45ae763c2e7e',
          createdAt: '2022-11-02T10:24:01.822Z',
        },
        _id: '63624541327d45ae763c2e7d',
      },
    ],
    annualRentGrowth: '12',
    mortgage: 0,
  },
  trending: false,
  isHidden: false,
  buyProcess: [
    {
      name: 'Heading 1',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      date: '2022-10-28T04:29:54.736Z',
      status: 'Completed',
    },
    {
      name: 'Heading 2',
      descripton:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      date: '2022-10-28T04:29:54.736Z',
      status: 'Completed',
    },
    {
      name: 'Heading 3',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      date: '2022-10-28T04:29:54.736Z',
      status: 'Pending',
    },
  ],
  createdAt: '2022-10-28T04:29:54.736Z',
  updatedAt: '2022-11-02T10:58:30.039Z',
  crowdsale: {
    status: 'completed',
    numberOfTokens: 164600,
    investmentReceived: true,
    investmentReceivedStatus: 'complete',
  },
  circle: {
    walletId: '1008982457',
  },
  mogulEquityBuyStatus: true,
  isTrending: false,
  status: 'Draft',
};

export const fieldInfo = {
  apn: { type: 'text', label: 'APN', update: true },
  // depth: { type: 'number', label: 'Depth' },
  // frontage: { type: 'number', label: 'Frontage' },
  lotnum: { type: 'text', label: 'Lot Number', update: true },
  lotsize1: { type: 'number', label: 'Lot Size1', update: true },
  lotsize2: { type: 'number', label: 'Lot Size2', update: true },
  // pooltype: { type: 'text' },
  area: { type: 'number', label: 'Area', update: true },
  blockNumber: { type: 'text', label: 'Block Number', update: true },
  locationType: { type: 'text', label: 'Location Type', update: true },
  country: { type: 'text', label: 'Country' },
  state: { type: 'text', label: 'State' },
  city: { type: 'text', label: 'City', update: true },
  areaTaxCode: { type: 'text', label: 'Area Tax Code', update: true },
  line1: { type: 'text', label: 'Line1', update: true },
  line2: { type: 'text', label: 'Line2', update: true },
  zipCode: { type: 'text', label: 'Zipcode' },
  latitude: { type: 'text', label: 'Latitude', update: true },
  longitude: { type: 'text', label: 'Longitude', update: true },
  propertyClass: { type: 'text', label: 'Property Class', update: true },
  propertyType: { type: 'text', label: 'Property Type', update: true },
  yearBuilt: { type: 'number', label: 'Year Built', update: true },
  bathTotal: { type: 'number', label: 'Totalbath', update: true },
  bedrooms: { type: 'number', label: 'Bedrooms', update: true },
  levels: { type: 'number', label: 'Levels', update: true },
  avmlastmonthvalue: { type: 'number', label: 'AVM Last Month Value', update: true },
  avmamountchange: { type: 'number', label: 'AVM Amount Change', update: true },
  avmpercentchange: {
    type: 'number',
    label: 'AVM Percentage Change(%)',
    min: 0,
    max: 100,
    update: true,
  },
};

export const otherDetailInfo = {
  title: { type: 'text', label: 'Title', update: true },
  _market: { type: 'select', label: 'Market', update: true },
  _manager: {
    type: 'text',
    label: 'Property Manager',
    disabled: true,
    value: '633bc237230b3dbfd5620ca4',
    update: true,
  },
  _owner: { type: 'select', label: 'Property Owner' },

  interestRate: { type: 'number', label: 'Interest Rate(%)', update: true },
  loanTerm: { type: 'number', label: 'Loan Term', update: true },

  isOccupied: { type: 'select', label: 'Occupied', bool: true, update: true },
  descriptionHeading: { type: 'text', label: 'Description Heading', update: true },
  descriptionSubHeading: { type: 'text', label: 'Description Sub-Heading', update: true },
  quote: { type: 'text', label: 'Quote', update: true },
  pool: { type: 'select', label: 'Pool', bool: true, update: true },
  fireplace: { type: 'select', label: 'Fireplace', bool: true, update: true },
  garage: { type: 'select', label: 'Garage', bool: true, update: true },
  isTrending: { type: 'select', label: 'Trending', bool: true, update: true },
  isHidden: { type: 'select', label: 'Hidden', bool: true, update: true },
};

export const financialInfo = {
  assetValue: { type: 'number', label: 'Asset Value($)', update: true },
  closingCost: { type: 'number', label: 'Closing Cost($)' },
  maintenanceReserve: { type: 'number', label: 'Maintainence Reserve($)' },
  vacancyReserve: { type: 'number', label: 'Vacancy Reserve($)' },
  mogulBuyerFee: { type: 'number', label: 'mogul Buyer Fee($)' },
  mogulSellerFee: { type: 'number', label: 'mogul Seller Fee($)' },
  currentEquity: { type: 'number', label: 'Current Equity($)', update: true },
  currentDebt: { type: 'number', label: 'Current Debt($)', update: true },
  sellerEquity: { type: 'number', label: 'Seller Equity($)' },
  mogulEquityToBuy: { type: 'number', label: 'mogul Equity To Buy($)' },
  mogulEquityToSell: { type: 'number', label: 'mogul Equity To Sell($)' },
  platformResaleFee: { type: 'number', label: 'Platform Resale Fee(%)', update: true },
  yearlyInvReturn: { type: 'number', label: 'yearly Return (%)', update: true },
  projectedInvGain: { type: 'number', label: 'Projected Investment Gain(%)', update: true },
  defaultRentGrowth: { type: 'number', label: 'Default Rent Growth (%)', update: true },
  defaultAnnualAppreciation: { type: 'number', label: 'Default Annual Appreciation (%)' },
  defaultTokensPurchased: { type: 'number', label: 'Default Tokens Purchased', update: true },
  leveragedCashflowMargin: { type: 'number', label: 'Leveraged Cashflow Margin(%)', update: true },
  defaultMonthlyRent: { type: 'number', label: 'Default Monthly Rent($)', update: true },
  contingencyVar1: { type: 'text', field: 'value' },
  contingencyVar2: { type: 'text', field: 'value' },
  contingencyVar3: { type: 'text', field: 'value' },
  contingencyVar4: { type: 'text', field: 'value' },
  // totalProfit: { type: 'text', label: 'total profit (%)' },
  // insertRate: { type: 'text', label: 'Intrest Rate (%)' },
  // loanTerm: { type: 'text', label: 'Loan Term' },
  // annual: { type: 'text', label: 'Default Annual Appreciation (%)' },
  // tokenPurchase: { type: 'text', label: 'Default Tokens Purchased' },
};

export const cashflowInfo = {
  monthlyRent: { type: 'number', label: 'Total Monthly Rent ($)', update: true },
  principal: { type: 'number', label: 'Principal ($)' },
  interest: { type: 'number', label: 'Interest ($)', update: true },
  taxes: { type: 'number', label: 'Taxes ($)', update: true },
  insurance: { type: 'number', label: 'Insurance ($)', update: true },
  annualRentGrowth: { type: 'number', label: 'Annual Rent Growth (%)', update: true },
  maxMaintenanceFee: { type: 'number', label: 'Max Maintenance Fee', update: true },
  maxVacancyFee: { type: 'number', label: 'Max vacancy Fee', update: true },
  propertyMgtFee: {
    type: 'number',
    label: 'Property Management Fee ($)',
    switch: true,
    update: true,
  },
  LLCAdministrationFee: {
    type: 'number',
    label: 'LLC Administration Fee ($)',
    switch: true,
    update: true,
  },
  HOAFee: { type: 'number', label: 'HOA Fee ($)', switch: true },
};

export const crowdSaleInfo = {
  numberOfTokens: { type: 'number', label: 'Total Tokens' },
  tokensForSale: { type: 'number', label: 'Tokens For Sale', disabled: true },
  startDate: { type: 'datetime-local', label: 'Start Date', update: true },
  stopDate: { type: 'datetime-local', label: 'End Date', update: true },
  pricePerToken: { type: 'number', label: 'Price Per Token', disabled: true },
};

export const marketDetailInfo = {
  marketName: { type: 'text', label: 'Name', required: true },
  state: { type: 'text', label: 'State', required: true },
  city: { type: 'text', label: 'City' },
  propertyGrowth: { type: 'number', label: 'Property Growth %', required: true },
  rentGrowth: { type: 'number', label: 'Rent Growth %', required: true },
  marketRating: { type: 'text', label: 'Market Rating', required: true },
};

export const checkUpdatedTab = {
  1: { name: 'attom', info: fieldInfo },
  2: { name: 'financials', info: financialInfo },
  3: { name: 'documents' },
  4: { name: 'images' },
  5: { name: 'crowdSale', info: crowdSaleInfo },
  6: { name: 'cashflow', info: cashflowInfo },
  7: { name: 'buyProcess' },
  9: { name: 'otherInfo', info: otherDetailInfo },
};
