export const AFFILIATE_MANAGEMENT_START = 'AFFILIATE_MANAGEMENT_START';
export const AFFILIATE_MANAGEMENT_FAIL = 'AFFILIATE_MANAGEMENT_FAIL';

export const GET_AFFILIATE_MANAGEMENT_LIST_SAGA = 'GET_AFFILIATE_MANAGEMENT_LIST_SAGA';
export const GET_AFFILIATE_MANAGEMENT_LIST_SUCCESS = 'GET_AFFILIATE_MANAGEMENT_LIST_SUCCESS';

export const APPROVE_AFFILIATE_START = 'APPROVE_AFFILIATE_START';
export const APPROVE_AFFILIATE_FAIL = 'APPROVE_AFFILIATE_FAIL';
export const APPROVE_AFFILIATE_SUCCESS = 'APPROVE_AFFILIATE_SUCCESS';
export const APPROVE_AFFILIATE_SAGA = 'APPROVE_AFFILIATE_SAGA';
