export const PropertyManagersData = [
    {
      _id:12321,
      company_name: "ABC",
      emailId:"text@123.com",
      registration_date:"27/02/2022",
      contact_person:"XYZ",
      status:"password sent",
      action:"",
      isBlackListed:true,
    },
    {
      _id:12320,
      company_name: "ABC",
      emailId:"text@123.com",
      registration_date:"27/02/2022",
      contact_person:"XYZ",
      status:"password sent",
      action:"",
      isBlackListed:true,
    },
    {
      _id:12322,
      company_name: "ABC",
      emailId:"text@123.com",
      registration_date:"27/02/2022",
      contact_person:"XYZ",
      status:"password sent",
      action:"",
      isBlackListed:false,
    },
    {
      _id:1232,
      company_name: "ABC",
      emailId:"text@123.com",
      registration_date:"27/02/2022",
      contact_person:"XYZ",
      status:"password sent",
      action:"",
      isBlackListed:false,
    },
    {
      _id:121,
      company_name: "ABC",
      emailId:"text@123.com",
      registration_date:"27/02/2022",
      contact_person:"XYZ",
      status:"password sent",
      action:"",
      isBlackListed:true,
    },
    {
      _id:1218,
      company_name: "ABC",
      emailId:"text@123.com",
      registration_date:"27/02/2022",
      contact_person:"XYZ",
      status:"password sent",
      action:"",
      isBlackListed:true,
    },
    {
      _id:12178,
      company_name: "ABC",
      emailId:"text@123.com",
      registration_date:"27/02/2022",
      contact_person:"XYZ",
      status:"password sent",
      action:"",
      isBlackListed:false,
    },
    {
      _id:12175,
      company_name: "ABC",
      emailId:"text@123.com",
      registration_date:"27/02/2022",
      contact_person:"XYZ",
      status:"password sent",
      action:"",
      isBlackListed:true,
    },
    {
      _id:12165,
      company_name: "ABC",
      emailId:"text@123.com",
      registration_date:"27/02/2022",
      contact_person:"XYZ",
      status:"password sent",
      action:"",
      isBlackListed:false,
    },
    {
      _id:12112,
      company_name: "ABC",
      emailId:"text@123.com",
      registration_date:"27/02/2022",
      contact_person:"XYZ",
      status:"password sent",
      action:"",
      isBlackListed:false,
    },
    {
      _id:121745,
      company_name: "ABC",
      emailId:"text@123.com",
      registration_date:"27/02/2022",
      contact_person:"XYZ",
      status:"password sent",
      action:"",
      isBlackListed:false,
    },
    {
      _id:121964,
      company_name: "ABC",
      emailId:"text@123.com",
      registration_date:"27/02/2022",
      contact_person:"XYZ",
      status:"password sent",
      action:"",
      isBlackListed:true,
    },
    {
      _id:121000,
      company_name: "ABC",
      emailId:"yash@123.com",
      registration_date:"27/02/2022",
      contact_person:"XYZ",
      status:"password sent",
      action:"",
      isBlackListed:true,
    },
    {
      _id:121632,
      company_name: "ABC",
      emailId:"text@123.com",
      registration_date:"27/02/2022",
      contact_person:"XYZ",
      status:"password sent",
      action:"",
      isBlackListed:true,
    }
    ];