// global
export const CMS_MANAGEMENT_START = 'CMS_MANAGEMENT_START';
export const CMS_MANAGEMENT_FAIL = 'CMS_MANAGEMENT_FAIL';

// get cms
export const GET_CMS_MANAGEMENT_SUCCESS = 'GET_CMS_MANAGEMENT_SUCCESS';
export const GET_CMS_MANAGEMENT_LIST_SAGA = 'GET_CMS_MANAGEMENT_LIST_SAGA';

// upload cms
export const UPLOAD_CMS_MANAGEMENT_SUCCESS = 'UPLOAD_CMS_MANAGEMENT_SUCCESS';
export const UPLOAD_CMS_MANAGEMENT_SAGA = 'UPLOAD_CMS_MANAGEMENT_SAGA';

// update cms
export const UPDATE_CMS_MANAGEMENT_SUCCESS = 'UPDATE_CMS_MANAGEMENT_SUCCESS';
export const UPDATE_CMS_MANAGEMENT_SAGA = 'UPDATE_CMS_MANAGEMENT_SAGA';

// add cms
export const ADD_CMS_MANAGEMENT_SUCCESS = 'ADD_CMS_MANAGEMENT_SUCCESS';
export const ADD_CMS_MANAGEMENT_SAGA = 'ADD_CMS_MANAGEMENT_SAGA';

// remove cms
export const REMOVE_CMS_MANAGEMENT_SUCCESS = 'REMOVE_CMS_MANAGEMENT_SUCCESS';
export const REMOVE_CMS_MANAGEMENT_SAGA = 'REMOVE_CMS_MANAGEMENT_SAGA';
