export const GET_TRANSACTION_MANAGEMENT_START = 'GET_TRANSACTION_MANAGEMENT_START';
export const GET_TRANSACTION_MANAGEMENT_FAIL = 'GET_TRANSACTION_MANAGEMENT_FAIL';
export const GET_TRANSACTION_MANAGEMENT_SUCCESS = 'GET_TRANSACTION_MANAGEMENT_SUCCESS';
export const GET_TRANSACTION_MANAGEMENT_LIST_SAGA = 'GET_TRANSACTION_MANAGEMENT_LIST_SAGA';

export const GET_PENDING_TRANSACTION_SUCCESS = 'GET_PENDING_TRANSACTION_SUCCESS';
export const GET_PENDING_TRANSACTION_LIST_SAGA = 'GET_PENDING_TRANSACTION_LIST_SAGA';

export const GET_PENDING_TRANSACTION_DETAILS_SUCCESS = 'GET_PENDING_TRANSACTION_DETAILS_SUCCESS';
export const GET_PENDING_TRANSACTION_DETAILS_SAGA = 'GET_PENDING_TRANSACTION_DETAILS_SAGA';

export const APPROVE_PENDING_TRANSACTION_SUCCESS = 'APPROVE_PENDING_TRANSACTION_SUCCESS';
export const APPROVE_PENDING_TRANSACTION_SAGA = 'APPROVE_PENDING_TRANSACTION_SAGA';
